# Generated by Django 2.0.2 on 2018-03-06 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('url', models.TextField(blank=True, primary_key=True, serialize=False)),
                ('king', models.TextField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('date', models.TextField(blank=True, null=True)),
                ('subject', models.TextField(blank=True, null=True)),
                ('chinese', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('place', models.TextField(blank=True, null=True)),
                ('book', models.TextField(blank=True, null=True)),
                ('nameid', models.TextField(blank=True, null=True)),
                ('placeid', models.TextField(blank=True, null=True)),
                ('bookid', models.TextField(blank=True, null=True)),
                ('korean', models.TextField(blank=True, null=True)),
                ('soldate', models.TextField(blank=True, null=True)),
                ('rdate', models.BigIntegerField(blank=True, null=True)),
                ('paragraph', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bangmok',
            fields=[
                ('personid', models.TextField(blank=True, primary_key=True, serialize=False)),
                ('url', models.TextField(blank=True, null=True)),
                ('relatives', models.TextField(blank=True, null=True)),
                ('chnname', models.TextField(blank=True, null=True)),
                ('residence', models.TextField(blank=True, null=True)),
                ('affilliation', models.TextField(blank=True, null=True)),
                ('king', models.TextField(blank=True, null=True)),
                ('korname', models.TextField(blank=True, null=True)),
                ('class_field', models.FloatField(blank=True, db_column='class', null=True)),
                ('year_of_pass', models.FloatField(blank=True, null=True)),
                ('rank', models.FloatField(blank=True, null=True)),
                ('exam_type', models.TextField(blank=True, null=True)),
                ('family_clan', models.TextField(blank=True, null=True)),
                ('birth', models.FloatField(blank=True, null=True)),
                ('death', models.FloatField(blank=True, null=True)),
                ('clan2', models.TextField(blank=True, null=True)),
                ('plastic', models.FloatField(blank=True, null=True)),
                ('age_of_pass', models.FloatField(blank=True, null=True)),
                ('career_length', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Figures',
            fields=[
                ('manid', models.TextField(blank=True, primary_key=True, serialize=False)),
                ('korname', models.TextField(blank=True, null=True)),
                ('chnname', models.TextField(blank=True, null=True)),
                ('korbon', models.TextField(blank=True, null=True)),
                ('chnbon', models.TextField(blank=True, null=True)),
                ('birth', models.IntegerField(blank=True, null=True)),
                ('death', models.IntegerField(blank=True, null=True)),
                ('job', models.TextField(blank=True, null=True)),
                ('nation', models.TextField(blank=True, null=True)),
                ('uci', models.TextField(blank=True, null=True)),
                ('examkey', models.TextField(blank=True, null=True)),
                ('key', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manid', models.TextField(blank=True, null=True)),
                ('officelevel', models.TextField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('paraid', models.TextField(blank=True, null=True)),
                ('jobid', models.BigIntegerField(blank=True, null=True)),
                ('level', models.FloatField(blank=True, null=True)),
                ('date', models.TextField(blank=True, null=True)),
                ('rdate', models.BigIntegerField(blank=True, null=True)),
                ('korname', models.TextField(blank=True, null=True)),
                ('chnname', models.TextField(blank=True, null=True)),
                ('gye', models.TextField(blank=True, null=True)),
                ('sa', models.TextField(blank=True, null=True)),
                ('jik', models.TextField(blank=True, null=True)),
                ('impossible', models.FloatField(blank=True, null=True)),
                ('temp', models.FloatField(blank=True, null=True)),
                ('nation', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
