# Generated by Django 2.0.2 on 2018-03-06 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_auto_20180306_2243'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='article',
            table='article',
        ),
        migrations.AlterModelTable(
            name='bangmok',
            table='bangmok',
        ),
    ]
