# Generated by Django 2.0.3 on 2018-10-15 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0003_auto_20180306_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='figures',
            name='checked',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='figures',
            name='deleted',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='figures',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
